name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifacts for deployment
        run: |
          cd dist/apps/backend-api/ && zip backend-api-release.zip ./* -r
          cd ../frontend-app/ && zip frontend-app-release.zip ./* -r

      - name: Upload backend-api artifact
        uses: actions/upload-artifact@v2
        with:
          name: backend-api
          path: backend-api-release.zip

      - name: Upload frontend-app artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend-app
          path: frontend-app-release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download backend-api artifact
        uses: actions/download-artifact@v2
        with:
          name: backend-api

      - name: Download frontend-app artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend-app

      - name: Deploy backend-api to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'NxWorkshop'
          slot-name: 'Production'
          publish-profile: ${{ secrets.NEXTJS_PUBLISHPROFILE }}
          package: .

      - name: Deploy frontend-app to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.ANGULAR_PUBLISHTOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: ""
